use_frameworks!

platform :ios, '8.0'

target 'TXKit_Example' do
  pod 'TXKit', :path => '../'

  target 'TXKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
